### PR TITLE
Include reference location in DataMsg instead of key

### PR DESCRIPTION
**Pull request by thSoft**

### CODE REVIEW

**Comment by ThomasWeiser** [comment]
Thanks for the PR!

`key` is needed especially for child queries.

You are right: Either a ref or a location string should be returned along with a `DataMsg` (additionally to `key`). A have to think about this a bit more.

**Comment by thSoft** [comment]
I think the DataMsg should contain a Ref, and both the location string and the key name should be computable from a Ref. If I have more time, I'll try to do this.

**Comment by ThomasWeiser** [comment]
This would require a different implementation of `Ref`. I have to think about this a bit more. (Can't work on it till Tuesday, I'm on a long weekend now.)

**Comment by ThomasWeiser** [comment]
`DataMsg` now contains a `Reference`, that can asked about the key, and the complete URL. Currently `DataMsg` also contains the key directly, which may be dropped.

Probably `DataMsg` should be turned into an opaque type, with accessor functions for its value, reference, key etc.

Also note that there is now a distinction between `Location` and `Reference`.  The former is constructed by pure functions and specifies the intended path into a Firebase. The latter is the result of a task (writing or querying) and represents the reference object of the Javascript-API of Firebase.

Thanks again for your input!

**Comment by thSoft** [comment]
Great, thanks!

Thomas Weiser notifications@github.com ezt írta (2015. május 23.,
szombat):

**Pull request closed without merging**
